# Local development overrides

url: http://localhost:4000

# don't use the remote theme for local development
remote_theme: false
theme: minimal-mistakes-jekyll

analytics:
  provider: false

sass:
  style: expanded